"""initial

Revision ID: 1378ca05a8de
Revises: 00f400a65209
Create Date: 2025-07-08 21:08:25.012852

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1378ca05a8de'
down_revision = '00f400a65209'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
