"""initial

Revision ID: 16e185bb60b3
Revises: a245208d2723
Create Date: 2025-07-08 22:35:12.093614

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e185bb60b3'
down_revision = 'a245208d2723'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
