"""initial

Revision ID: 23c68a80b1ea
Revises: 433b8f9af1be
Create Date: 2025-07-08 18:36:30.205239

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c68a80b1ea'
down_revision = '433b8f9af1be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
