"""initial

Revision ID: 433b8f9af1be
Revises: d71a696d60ec
Create Date: 2025-07-08 17:14:57.410969

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433b8f9af1be'
down_revision = 'd71a696d60ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
