"""initial

Revision ID: 4bbbb7812798
Revises: 23c68a80b1ea
Create Date: 2025-07-08 18:37:49.377106

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbbb7812798'
down_revision = '23c68a80b1ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
