"""initial

Revision ID: 4da507629141
Revises: f3b0bbf51617
Create Date: 2025-07-08 22:21:14.583662

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da507629141'
down_revision = 'f3b0bbf51617'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
