"""initial

Revision ID: 611777952053
Revises: 4bbbb7812798
Create Date: 2025-07-08 18:38:59.614441

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611777952053'
down_revision = '4bbbb7812798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
