"""initial

Revision ID: 84118d4fd843
Revises: e64d60e1978d
Create Date: 2025-07-08 22:01:25.944813

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84118d4fd843'
down_revision = 'e64d60e1978d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
