"""initial

Revision ID: 92593dcc63d5
Revises: e623942e7078
Create Date: 2025-07-08 15:06:13.055288

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92593dcc63d5'
down_revision = 'e623942e7078'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
