"""initial

Revision ID: d6ff9c1229f2
Revises: 84118d4fd843
Create Date: 2025-07-08 22:11:53.446112

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ff9c1229f2'
down_revision = '84118d4fd843'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
