"""initial

Revision ID: d71a696d60ec
Revises: 92593dcc63d5
Create Date: 2025-07-08 17:08:36.719018

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71a696d60ec'
down_revision = '92593dcc63d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
