"""initial

Revision ID: e64d60e1978d
Revises: 1378ca05a8de
Create Date: 2025-07-08 21:57:26.910155

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64d60e1978d'
down_revision = '1378ca05a8de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
