"""initial

Revision ID: f3b0bbf51617
Revises: d6ff9c1229f2
Create Date: 2025-07-08 22:15:18.129635

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b0bbf51617'
down_revision = 'd6ff9c1229f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
